=== ProfJerry/-/数据/数据-IPR/D3/MIC-model-class1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:uml="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" targetNamespace="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:simpleType name="DNType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:complexType name="DNSetType">
		<xsd:sequence>
			<xsd:element name="dn" type="uml:DNType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManagedObject_T">
		<xsd:sequence>
			<xsd:element name="objectClass" type="xsd:string"/>
			<xsd:element name="objectInstance" type="uml:DNType"/>
		</xsd:sequence>
	</xsd:complexType>
	<!--COMMON CONFIG-->
	<xsd:complexType name="Router_T" abstract="true">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element name="userLabel" type="uml:UserLabelType_T"/>
					<!--<xsd:element name="interfaceNum" type="xsd:integer"/>-->
					<xsd:element name="actions" type="uml:ActionType"/>
					<xsd:element name="assRouterList" type="uml:DNSetType"/>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="CRType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="crId" type="xsd:string"/>
					<xsd:element name="routeId" type="xsd:string"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ARType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="arId" type="xsd:string"/>
					<xsd:element name="accessId" type="uml:AID_T"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ASRType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="asrId" type="xsd:string"/>
					<xsd:element name="routeId" type="xsd:string"/>
					<xsd:element name="accessId" type="xsd:string"/>
					<xsd:element name="routeIdPool" type="uml:routeIdPool_T"/>
					<xsd:element name="accessIdPool" type="uml:accessIdPool_T"/>
					<!--<xsd:element name="memRelQueryInterval" type="xsd:integer"/>-->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<!--OutputInstance-->
	<xsd:complexType name="OutputInstanceType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="uml:AR_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:CR_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:ASR_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:MICModule_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:MMC_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:MicGroupTable_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:MicMemTable_C" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:element name="outputInstanceList" type="uml:OutputInstanceType"/>
	<!--KEY ELEMENTS-->
	<xsd:element name="CR_C" type="uml:CRType_T"/>
	<xsd:element name="AR_C" type="uml:ARType_T"/>
	<xsd:element name="ASR_C" type="uml:ASRType_T"/>
	<xsd:element name="MMC_C" type="uml:MMC_T"/>
	<xsd:element name="MICModule_C" type="uml:MICModule_T"/>
	<xsd:element name="MicMemTable_C" type="uml:MicMemTable_T"/>
	<xsd:element name="MicGroupTable_C" type="uml:MicGroupTable_T"/>
	<!--MIC Related-->
	<xsd:complexType name="MICModule_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence minOccurs="1">
					<xsd:element name="MICModuleID" type="xsd:string"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="MMC_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence>
					<xsd:element name="mmcId" type="xsd:string"/>
					<xsd:element name="userLabel" type="xsd:string"/>
					<xsd:element name="servAddr" type="uml:AID_T"/>
					<xsd:element name="maxMemSourceCount" type="xsd:unsignedInt"/>
					<xsd:element name="maxMemReceiverCount" type="xsd:unsignedInt"/>
					<xsd:element name="msiBrodInterval" type="xsd:unsignedInt"/>
					<xsd:element name="servExpiQueryWaitTime" type="xsd:unsignedInt"/>
					<!--<xsd:element name="micGroupTable" type="MicGroupTableType"/>-->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="MicMemTable_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence>
					<xsd:element name="micMemTableId" type="xsd:string"/>
					<xsd:sequence maxOccurs="unbounded">
						<xsd:element name="micMemInfo" type="xsd:string"/>
					</xsd:sequence>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="MicGroupTable_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence>
					<xsd:element name="micGroupTableId" type="xsd:string"/>
					<xsd:sequence maxOccurs="unbounded">
						<xsd:element name="micGroupInfo" type="xsd:string"/>
					</xsd:sequence>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<!--	<xsd:complexType name="IfTable_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence minOccurs="1">
					<xsd:element name="ifTableId" type="xsd:string"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="IfTable_C" type="uml:IfTable_T"/>
	<xsd:complexType name="If_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence>
					<xsd:element name="ifId" type="xsd:string"/>
					<xsd:element name="ifAddr" type="uml:RID_T"/>
					<xsd:element name="areaId" type="uml:areaId_T"/>
					<xsd:element name="ifType" type="uml:ifType_T"/>
					<xsd:element name="nbrRid" type="uml:RID_T"/>
					<xsd:element name="ifState" type="uml:ifState_T"/>
					<xsd:element name="assIfList" type="uml:DNSetType"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="ifType_T">
		<xsd:restriction base="xsd:integer">
			<xsd:enumeration value="1"/>
			<xsd:enumeration value="2"/>
			<xsd:enumeration value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ifState_T">
		<xsd:restriction base="xsd:integer">
			<xsd:enumeration value="0"/>
			<xsd:enumeration value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="If_C" type="uml:If_T"/>-->
	<!--BASIC TYPES-->
	<xsd:simpleType name="UserLabelType_T">
		<xsd:annotation>
			<xsd:documentation>User Identifiable Device Label or Name.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="256"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="ActionType">
		<xsd:choice>
			<xsd:element name="notifyObjectionCreation" type="xsd:string" fixed="CREATED"/>
			<xsd:element name="notifyObjectionDelection" type="xsd:string" fixed="DELETED"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="routeIdPool_T">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="routeId" type="uml:RID_T"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="accessIdPool_T">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="accessId" type="uml:AID_T"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="RID_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
			<xsd:pattern value="[0123456789ABCDEF]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AID_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
			<xsd:pattern value="[0123456789ABCDEF]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MSI_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
			<xsd:pattern value="[0123456789ABCDEF]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MRI_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
			<xsd:pattern value="[0123456789ABCDEF]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="areaId_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
			<xsd:pattern value="[0123456789ABCDEF]+"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== ProfJerry/-/数据/数据-IPR/D3/MIC_CONF_instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml:outputInstanceList xmlns:uml="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel MIC-model-class1.xsd">
<uml:AR_C>
	<uml:objectClass>AR_C</uml:objectClass>
	<uml:objectInstance>arId=AR101</uml:objectInstance>
	<uml:userLabel>AR-101</uml:userLabel>
	<uml:actions>
		<uml:notifyObjectionCreation>CREATED</uml:notifyObjectionCreation>
	</uml:actions>
	<uml:assRouterList>
		<uml:dn>asrId=ASR101</uml:dn>
	</uml:assRouterList>
	<uml:arId>AR101</uml:arId>
	<uml:accessId>A144551DF49ADE37</uml:accessId>
</uml:AR_C>

<uml:AR_C>
	<uml:objectClass>AR_C</uml:objectClass>
	<uml:objectInstance>arId=AR102</uml:objectInstance>
	<uml:userLabel>AR-102</uml:userLabel>
	<uml:actions>
		<uml:notifyObjectionCreation>CREATED</uml:notifyObjectionCreation>
	</uml:actions>
	<uml:assRouterList>
		<uml:dn>asrId=ASR101</uml:dn>
	</uml:assRouterList>
	<uml:arId>AR102</uml:arId>
	<uml:accessId>4DC0935835D11E58</uml:accessId>
</uml:AR_C>

<uml:ASR_C>
	<uml:objectClass>ASR_C</uml:objectClass>
	<uml:objectInstance>asrId=ASR101</uml:objectInstance>
	<uml:userLabel>ASR-101</uml:userLabel>
	<uml:actions>
		<uml:notifyObjectionCreation>CREATED</uml:notifyObjectionCreation>
	</uml:actions>
	<uml:assRouterList>
		<uml:dn>arId=AR101</uml:dn>
		<uml:dn>arId=AR102</uml:dn>
	</uml:assRouterList>
	<uml:asrId>ASR-101</uml:asrId>
	<uml:routeId>5DBA9B93C355A576600A3E1EDE5C396F</uml:routeId>
	<uml:accessId>86172636B3F1AB91</uml:accessId>
	<uml:routeIdPool>
		<uml:routeId>97864A796B6F2E55CDA680285FE680E7</uml:routeId>
		<uml:routeId>FE458CF6C49A4E25F8C80985FC5F23B5</uml:routeId>
		<uml:routeId>94F7B931E1FA6604CB9AEA5C2DE4F7BA</uml:routeId>
		<uml:routeId>962F329D772795332149386AE179AA26</uml:routeId>
		<uml:routeId>68064A6DC2289B33B8DCCB1D9C45EFC1</uml:routeId>
	</uml:routeIdPool>
	<uml:accessIdPool>
		<uml:accessId>F49042F2E8F5F21D</uml:accessId>
		<uml:accessId>EBA6C156075BE33B</uml:accessId>
		<uml:accessId>1B3CEEDA90CBDF65</uml:accessId>
		<uml:accessId>E7EDA08BB1721E31</uml:accessId>
		<uml:accessId>8AFA2F771DCE63D8</uml:accessId>
		<uml:accessId>7A1774897558D887</uml:accessId>
		<uml:accessId>D1967592FAE78104</uml:accessId>
		<uml:accessId>35D368979BF2A590</uml:accessId>
		<uml:accessId>451BE11315ACCB73</uml:accessId>
		<uml:accessId>DEBF0193646502F3</uml:accessId>
	</uml:accessIdPool>
</uml:ASR_C>

<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crId=CR101</uml:objectInstance>
	<uml:userLabel>CR-101</uml:userLabel>
	<uml:actions>
		<uml:notifyObjectionCreation>CREATED</uml:notifyObjectionCreation>
	</uml:actions>
	<uml:assRouterList>
		<uml:dn>asrId=ASR101</uml:dn>
	</uml:assRouterList>
	<uml:crId>CR101</uml:crId>
	<uml:routeId>2AF70D6BF067D37ED41DCCA704C38B4F</uml:routeId>
</uml:CR_C>

<uml:MMC_C>
	<uml:objectClass>MMC_C</uml:objectClass>
	<uml:objectInstance>mmcId=MMC101</uml:objectInstance>
	<uml:mmcId>MMC101</uml:mmcId>
	<uml:userLabel>MMC-101</uml:userLabel>
	<uml:servAddr>32C40D35F2716092</uml:servAddr>
	<uml:maxMemSourceCount>9999</uml:maxMemSourceCount>
	<uml:maxMemReceiverCount>9999</uml:maxMemReceiverCount>
	<uml:msiBrodInterval>20</uml:msiBrodInterval>
	<uml:servExpiQueryWaitTime>20</uml:servExpiQueryWaitTime>
</uml:MMC_C>
<uml:MicGroupTable_C>
	<uml:objectClass>MicGroupTable_C</uml:objectClass>
	<uml:objectInstance>mmcId=MMC101,micGroupTableId=MMCGPTAB101</uml:objectInstance>
	<uml:micGroupTableId>MMCGPTAB101</uml:micGroupTableId>
	<uml:micGroupInfo>servMSI:44E71C3FA96B055D</uml:micGroupInfo>
</uml:MicGroupTable_C>
<uml:MicMemTable_C>
	<uml:objectClass>MicMemTable_C</uml:objectClass>
	<uml:objectInstance>mmcId=MMC101,micGroupTableId=MMCGPTAB101,micMemTableId=MICMEMTAB10001</uml:objectInstance>
	<uml:micMemTableId>MICMEMTAB10001</uml:micMemTableId>
	<uml:micMemInfo>memAid=C6CB13417DBB3155,memAsrAid=86172636B3F1AB91</uml:micMemInfo>
	<uml:micMemInfo>memAid=C8DFAD1B385B5C9C,memAsrAid=86172636B3F1AB91</uml:micMemInfo>
</uml:MicMemTable_C>

</uml:outputInstanceList>
