=== ProfJerry/-/数据/IRP-model-class3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:uml="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" targetNamespace="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:simpleType name="DNType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:complexType name="DNSetType">
		<xsd:sequence>
			<xsd:element name="dn" type="uml:DNType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManagedObject_T">
		<xsd:sequence>
			<xsd:element name="objectClass" type="xsd:string"/>
			<xsd:element name="objectInstance" type="uml:DNType"/>
		</xsd:sequence>
	</xsd:complexType>
	<!--COMMON CONFIG-->
	<xsd:complexType name="Router_T" abstract="true">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence>
					<xsd:element name="IRPModule" type="uml:IRPModuleType"/>
					<xsd:element name="assRouterList" type="uml:DNSetType"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="accessIDPool_T" abstract="true">
		<xsd:sequence>
			<xsd:element name="accessID" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="routeIDPool_T" abstract="true">
		<xsd:sequence>
			<xsd:element name="routeID" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CRType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="crID" type="xsd:string"/>
					<xsd:element name="routeID" type="xsd:string"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ARType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="arID" type="xsd:string"/>
					<xsd:element name="accessID" type="xsd:string"/>
					<xsd:element name="accessIDPool" type="uml:accessIDPool_T"/>
					<xsd:element name="routeIDPool" type="uml:routeIDPool_T"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ASRType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="asrID" type="xsd:string"/>
					<xsd:element name="routeID" type="xsd:string"/>
					<xsd:element name="accessID" type="xsd:string"/>
					<!--<xsd:element name="memRelQueryInterval" type="xsd:integer"/>-->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="InstanceOutputType">
		<xsd:sequence>
			<xsd:element ref="uml:CR_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:ASR_C" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="outputInstanceList" type="uml:InstanceOutputType"/>
	
	<!--KEY ELEMENTS-->
	<xsd:element name="CR_C" type="uml:CRType_T"/>
	<!--<xsd:element name="AR_C" type="uml:ARType_T"/>-->
	<xsd:element name="ASR_C" type="uml:ASRType_T"/>
	
	<!--IRP Related-->
	<xsd:complexType name="IRPModuleType">
		<xsd:sequence>
			<xsd:element name="IRPModuleID" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== ProfJerry/-/数据/IRP_CONF_instance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml:outputInstanceList xmlns:uml="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel IRP-model-class3.xsd">
<!--<uml:outputInstanceList>-->
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR101</uml:objectInstance>
	<uml:IRPModule>
		<uml:IRPModuleID>CR101IRP</uml:IRPModuleID>
	</uml:IRPModule>
	<uml:assRouterList>
		<uml:dn>crID=CR102</uml:dn>
		<uml:dn>crID=CR103</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR101</uml:crID>
	<uml:routeID>747B1B8C37568C69575B2307C05618A5</uml:routeID>
</uml:CR_C>
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR102</uml:objectInstance>
	<uml:IRPModule>
		<uml:IRPModuleID>CR102IRP</uml:IRPModuleID>
	</uml:IRPModule>
	<uml:assRouterList>
		<uml:dn>crID=CR101</uml:dn>
		<uml:dn>crID=CR104</uml:dn>
		<uml:dn>asrID=ASR101</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR102</uml:crID>
	<uml:routeID>AD1B385B5C9CC6CBAC9A38D00AD0DE76</uml:routeID>
</uml:CR_C>

<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR103</uml:objectInstance>
	<uml:IRPModule>
		<uml:IRPModuleID>CR103IRP</uml:IRPModuleID>
	</uml:IRPModule>
	<uml:assRouterList>
		<uml:dn>crID=CR101</uml:dn>
		<uml:dn>crID=CR104</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR103</uml:crID>
	<uml:routeID>C572949EC2AE9A0A7FECB3EB5F1E670D</uml:routeID>
</uml:CR_C>
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR104</uml:objectInstance>
	<uml:IRPModule>
		<uml:IRPModuleID>CR104IRP</uml:IRPModuleID>
	</uml:IRPModule>
	<uml:assRouterList>
		<uml:dn>crID=CR102</uml:dn>
		<uml:dn>crID=CR103</uml:dn>
		<uml:dn>asrID=ASR102</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR104</uml:crID>
	<uml:routeID>C572949EC2AE9A0A2BB2BC82D272E253</uml:routeID>
</uml:CR_C>

<uml:ASR_C>
	<uml:objectClass>ASR_C</uml:objectClass>
	<uml:objectInstance>asrID=ASR101</uml:objectInstance>
	<uml:IRPModule>
		<uml:IRPModuleID>ASR101IRP</uml:IRPModuleID>
	</uml:IRPModule>
	<uml:assRouterList>
		<uml:dn>CR102</uml:dn>
	</uml:assRouterList>
	<uml:asrID>ASR101</uml:asrID>
	<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
	<uml:accessID>91060367ACB9B41C</uml:accessID>
</uml:ASR_C>

<uml:ASR_C>
	<uml:objectClass>ASR_C</uml:objectClass>
	<uml:objectInstance>asrID=ASR102</uml:objectInstance>
	<uml:IRPModule>
		<uml:IRPModuleID>ASR102IRP</uml:IRPModuleID>
	</uml:IRPModule>
	<uml:assRouterList>
		<uml:dn>CR104</uml:dn>
	</uml:assRouterList>
	<uml:asrID>ASR102</uml:asrID>
	<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
	<uml:accessID>91060367ACB9B41C</uml:accessID>
</uml:ASR_C>

</uml:outputInstanceList>
