=== ProfJerry/-/数据/数据-IPR/D1/IRP-model-class1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:uml="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" targetNamespace="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xsd:simpleType name="DNType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:complexType name="DNSetType">
		<xsd:sequence>
			<xsd:element name="dn" type="uml:DNType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManagedObject_T">
		<xsd:sequence>
			<xsd:element name="objectClass" type="xsd:string"/>
			<xsd:element name="objectInstance" type="uml:DNType"/>
		</xsd:sequence>
	</xsd:complexType>
	<!--COMMON CONFIG-->
	<xsd:complexType name="Router_T" abstract="true">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element name="userLabel" type="uml:UserLabelType_T"/>
					<xsd:element name="interfaceNum" type="xsd:integer"/>
					<xsd:element name="actions" type="uml:ActionType"/>
					<xsd:element name="assRouterList" type="uml:DNSetType"/>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="CRType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="crID" type="xsd:string"/>
					<xsd:element name="routeID" type="xsd:string"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ARType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="arID" type="xsd:string"/>
					<xsd:element name="accessID" type="xsd:string"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ASRType_T">
		<xsd:complexContent>
			<xsd:extension base="uml:Router_T">
				<xsd:sequence>
					<xsd:element name="asrID" type="xsd:string"/>
					<xsd:element name="routeID" type="xsd:string"/>
					<xsd:element name="accessID" type="xsd:string"/>
					<xsd:element name="routeIDPool" type="uml:routeIDPool_T"/>
					<xsd:element name="accessIDPool" type="uml:accessIDPool_T"/>
					<!--<xsd:element name="memRelQueryInterval" type="xsd:integer"/>-->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="OutputInstanceType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="uml:CR_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:ASR_C" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element ref="uml:IRPModule_C" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:element name="outputInstanceList" type="uml:OutputInstanceType"/>
	
	<!--KEY ELEMENTS-->
	<xsd:element name="CR_C" type="uml:CRType_T"/>
	<!--<xsd:element name="AR_C" type="uml:ARType_T"/>-->
	<xsd:element name="ASR_C" type="uml:ASRType_T"/>
	<!--IRP Related-->
	<xsd:complexType name="IRPModule_T">
		<xsd:complexContent>
			<xsd:extension base="uml:ManagedObject_T">
				<xsd:sequence minOccurs="0">
					<xsd:element name="IRPModuleID" type="xsd:string"/>
					<xsd:element name="areaId" type="uml:AeraID_T"/>
<!--					<xsd:element name="routerPriority" type="xsd:integer"/>
					<xsd:element name="SecType" type="uml:SecType_T"/>
					<xsd:element name="SecCode" type="uml:SecCode_T"/>-->
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="IRPModule_C" type="uml:IRPModule_T"/>
	<!--	<xsd:complexType name="IRP_SecType_T">
		<xsd:sequence>
			<xsd:element name="secType" type="uml:secType_T"/>
			-->
	<!--<xsd:element name="secCode" type="uml:secCodeType_T"/>-->
	<!--
		</xsd:sequence>
	</xsd:complexType>-->
	<xsd:simpleType name="SecType_T">
		<xsd:restriction base="xsd:unsignedInt">
			<xsd:enumeration value="0"/>
			<xsd:enumeration value="1"/>
			<xsd:enumeration value="2"/>
			<xsd:enumeration value="3"/>
			<xsd:enumeration value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SecCode_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="256"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!--BASIC TYPES-->
	<xsd:simpleType name="UserLabelType_T">
		<xsd:annotation>
			<xsd:documentation>User Identifiable Device Label or Name.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="256"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="ActionType">
		<xsd:choice>
			<xsd:element name="notifyObjectionCreation" type="xsd:string" fixed="CREATED"/>
			<xsd:element name="notifyObjectionDelection" type="xsd:string" fixed="DELETED"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="routeIDPool_T">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="routeID" type="uml:RID_T"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="accessIDPool_T">
		<xsd:sequence>
			<xsd:element name="accessID" type="uml:AID_T"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="RID_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AID_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AeraID_T">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== ProfJerry/-/数据/数据-IPR/D1/IRP_CONF_instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<uml:outputInstanceList xmlns:uml="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ws.zc/xml-namespace/informationModel/UMLModelGenericModel IRP-model-class1.xsd">
<!--<uml:outputInstanceList>-->
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR101</uml:objectInstance>
	<uml:userLabel>CR-101</uml:userLabel>
	<uml:interfaceNum>4</uml:interfaceNum>
	<uml:actions>
		<uml:notifyObjectionCreation>CREATED</uml:notifyObjectionCreation>
	</uml:actions>
	<uml:assRouterList>
		<uml:dn>crID=CR102</uml:dn>
		<uml:dn>crID=CR103</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR101</uml:crID>
	<uml:routeID>747B1B8C37568C69575B2307C05618A5</uml:routeID>
</uml:CR_C>
<uml:IRPModule_C>
	<uml:objectClass>IRPModule_C</uml:objectClass>
	<uml:objectInstance>crID=CR101,IRPModuleID=CR101IRP</uml:objectInstance>
	<uml:IRPModuleID>CR101IRP</uml:IRPModuleID>
	<uml:areaId>C8DF</uml:areaId>
</uml:IRPModule_C>
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR102</uml:objectInstance>
	<uml:userLabel>CR-102</uml:userLabel>
	<uml:interfaceNum>4</uml:interfaceNum>
	<uml:assRouterList>
		<uml:dn>crID=CR101</uml:dn>
		<uml:dn>crID=CR104</uml:dn>
		<uml:dn>asrID=ASR101</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR102</uml:crID>
	<uml:routeID>AD1B385B5C9CC6CBAC9A38D00AD0DE76</uml:routeID>
</uml:CR_C>
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR103</uml:objectInstance>
	<uml:userLabel>CR-103</uml:userLabel>
	<uml:interfaceNum>4</uml:interfaceNum>
	<uml:assRouterList>
		<uml:dn>crID=CR101</uml:dn>
		<uml:dn>crID=CR104</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR103</uml:crID>
	<uml:routeID>C572949EC2AE9A0A7FECB3EB5F1E670D</uml:routeID>
</uml:CR_C>
<uml:CR_C>
	<uml:objectClass>CR_C</uml:objectClass>
	<uml:objectInstance>crID=CR104</uml:objectInstance>
	<uml:userLabel>CR-104</uml:userLabel>
	<uml:interfaceNum>4</uml:interfaceNum>
	<uml:assRouterList>
		<uml:dn>crID=CR102</uml:dn>
		<uml:dn>crID=CR103</uml:dn>
		<uml:dn>asrID=ASR102</uml:dn>
	</uml:assRouterList>
	<uml:crID>CR104</uml:crID>
	<uml:routeID>C572949EC2AE9A0A2BB2BC82D272E253</uml:routeID>
</uml:CR_C>

<uml:ASR_C>
	<uml:objectClass>ASR_C</uml:objectClass>
	<uml:objectInstance>asrID=ASR101</uml:objectInstance>
	<uml:userLabel>ASR-101</uml:userLabel>
	<uml:interfaceNum>4</uml:interfaceNum>
	<uml:assRouterList>
		<uml:dn>CR102</uml:dn>
	</uml:assRouterList>
	<uml:asrID>ASR101</uml:asrID>
	<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
	<uml:accessID>91060367ACB9B41C</uml:accessID>
	<uml:routeIDPool>
		<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
	</uml:routeIDPool>
	<uml:accessIDPool>
		<uml:accessID>91060367ACB9B41C</uml:accessID>
	</uml:accessIDPool>
</uml:ASR_C>

<uml:ASR_C>
	<uml:objectClass>ASR_C</uml:objectClass>
	<uml:objectInstance>asrID=ASR102</uml:objectInstance>
	<uml:userLabel>ASR-102</uml:userLabel>
	<uml:interfaceNum>4</uml:interfaceNum>
	<uml:assRouterList>
		<uml:dn>CR104</uml:dn>
	</uml:assRouterList>
	<uml:asrID>ASR102</uml:asrID>
	<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
	<uml:accessID>91060367ACB9B41C</uml:accessID>
	<uml:routeIDPool>
		<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
		<uml:routeID>C20CD53FF1E5983DB4067B04CF1CA20C</uml:routeID>
	</uml:routeIDPool>
	<uml:accessIDPool>
		<uml:accessID>91060367ACB9B41C</uml:accessID>
	</uml:accessIDPool>
</uml:ASR_C>
</uml:outputInstanceList>
